version: '4.27.1'
services:
  service_user:
    container_name: service_user
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
     - "/var/lib/mongodb-user:/data/db"