version: '4.27.1'
services:
  app:
    container_name: service_user
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db