name: Build Test and push
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose for testing
        run: |
          docker-compose up -d && docker ps && sleep 5

      - name: Run tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/user_collection.json
          reporters: cli
          iterationCount: 1

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}